# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for rtfblog.

language: go

go:
    - 1.2.1
    - tip

before_install:
    - go get code.google.com/p/go-html-transform/css/selector
    - go get code.google.com/p/go.tools/cmd/vet
    - go get -v code.google.com/p/go.tools/cmd/cover
    - go get -v github.com/mattn/goveralls

install:
    - go get -d -v ./...
    - ./scripts/genversion.sh
    - go build -v src/*.go

script:
    - go vet -x src/*.go
    - go test -covermode=count -coverprofile=profile.cov -v ./src/...

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
