# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for rtfblog.

language: go

go:
    - 1.13
    - tip

before_install:
    - nvm install 15.8
    - nvm use 15.8
    - go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls
    - go get -v github.com/steinbacher/goose/cmd/goose
    - go get -v github.com/go-bindata/go-bindata/...
    - npm install -g grunt-cli bower browserify json
    - sudo apt-get purge postgresql-client-9.5
    - sudo apt-get install postgresql-server-dev-9.4
    - sudo /etc/init.d/postgresql stop

script:
    - make
    - ./scripts/run-pg-tests.sh
    - ./scripts/run-sqlite-tests.sh

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
