# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for rtfblog.

language: go

go:
    - 1.2.1
    - tip

before_install:
    - go get code.google.com/p/go-html-transform/css/selector
    - go get code.google.com/p/go.tools/cmd/vet

install: go get -d -v ./... && go build -v .

script:
    - go vet -x .
    - go test -v .
