# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for rtfblog.

language: go

go:
    - 1.4
    - 1.5
    - tip

before_install:
    - go get -v golang.org/x/tools/cmd/vet
    - go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls
    - go get -v bitbucket.org/liamstask/goose/cmd/goose
    - go get -v github.com/jteeuwen/go-bindata
    - npm install -g grunt-cli bower browserify json
    - sudo /etc/init.d/postgresql stop

script:
    - make
    - ./scripts/run-pg-tests.sh
    - ./scripts/run-sqlite-tests.sh

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
