name: Run tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Diagnostics
      run: |
        pwd
        go env
        ls $HOME/go/bin
        echo $GOPATH
        echo $GOBIN
        echo $PATH
        echo $GITHUB_ACTIONS
        id -u
        id -un
        id -g
        id -gn
        ls -la

    - name: Build builder container
      run: make dbuild

    - name: Build the output
      run: make drun

    # chown back after 'make drun' has chown'ed it inside the container:
    - run: sudo chown -R runner:docker .

    # TODO: go tool cover -func=coverage.out | grep total: | awk '{ print $3 }' | tr -d %
    # - name: Run go tool cover
    #   run: go tool cover -func=coverage.out -o=coverage.out

    - name: Install Go dependencies for tests
      run: |
        go get -v golang.org/x/tools/cmd/cover
        go install -tags 'postgres,sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.2
        go install github.com/go-bindata/go-bindata/go-bindata@latest

    - name: Stop postgres
      run: |
        sudo /etc/init.d/postgresql stop

    - name: Run pg tests
      run: ./scripts/run-pg-tests.sh
      env:
        GOPATH: /home/runner/go

    - name: Run sqlite tests
      run: ./scripts/run-sqlite-tests.sh
      env:
        GOPATH: /home/runner/go

    # TODO: coverage badge needs to be reimplemented on GH actions somehow...
    # - name: post coverage
    #   if: success() || failure()
    #   run: /home/runner/go/bin/goveralls -coverprofile=profile.cov -service=travis-ci
