name: Run tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Prepare nvm
      run: |
        . $HOME/.nvm/nvm.sh > /dev/null 2>&1 || true
        nvm install 18.18
        nvm use 18.18

    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install Go dependencies
      run: |
        go get -v golang.org/x/tools/cmd/cover
        go install github.com/mattn/goveralls@latest
        go install -tags 'postgres,sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.2
        go install github.com/go-bindata/go-bindata/go-bindata@latest

    - name: Check Go dependencies
      run: |
        go env
        ls $HOME/go/bin
        echo $GOPATH
        echo $GOBIN
        echo $PATH

    # I used to do 'npm install -g grunt-cli' as well, but grunt already exists
    # in GH runner:
    #   npm ERR! File exists: /usr/local/bin/grunt
    #   npm ERR! Remove the existing file and try again, or run npm
    - name: Install bower, browserify
      run: npm install -g bower browserify

    - name: Run make
      run: make
      env:
        GOPATH: /home/runner/go

    - name: Run go tool cover
      run: go tool cover -func=coverage.out -o=coverage.out

    - name: Stop postgres
      run: |
        sudo /etc/init.d/postgresql stop

    - name: Run pg tests
      run: ./scripts/run-pg-tests.sh
      env:
        GOPATH: /home/runner/go

    - name: Run sqlite tests
      run: ./scripts/run-sqlite-tests.sh
      env:
        GOPATH: /home/runner/go

    # TODO: coverage badge needs to be reimplemented on GH actions somehow...
    # - name: post coverage
    #   if: success() || failure()
    #   run: /home/runner/go/bin/goveralls -coverprofile=profile.cov -service=travis-ci
